### PR TITLE
Workspace based completions

### PR DESCRIPTION
**Pull request by frepond**
Hi @yuce, I've added an escript to generate completions from workspace `*.beam`, you have a new command for generating them. Workspace completion file is located in .erl_workspace.json and it's now used by your completion code if it exists. I've also used the escript to update the Erlang stdlibs to 19.3.

The change is a bit quick and dirty but I think it's useful anyway. I'll probably being adding new features.

Kind Regards,

Federico

### CODE REVIEW

**Comment by yuce** [comment]
Hi Federico! Thanks a lot for your contribution! I'll check the PR and will approve soon.

**Comment by yuce** [comment]
@frepond You have some great code in the PR, but as far as I see auto-indent requires an emacs installation. Is that accurate ?

**Comment by frepond** [comment]
Hi @yuce, yes you're correct, you need emacs installed. I've reviwed the other version based erl_tidy and I've found it to invasive, it does formatting but also do some refactor on your code. I should test the extension further but it should fail silently if you don't have emacs installed and just not work.

**Comment by yuce** [comment]
Would it be too much trouble for you to remove the Emacs specific code from the PR? I guess there are only a few people who would have both VSCode and Emacs installed and use VSCode for their Erlang programming so the benefit of having an Emacs-based auto-indenting feature is very low. There should be a way to force VSCode to do the auto-indent correctly using VSCode API or some setting.

**Comment by frepond** [comment]
I can remove it completely or leave one based only on Erlang with erl_tidy, I've tweaked it a bit to provide decent formatting. Wherever you prefer.

**Comment by yuce** [comment]
I think the right way for this PR is just removing the auto-indent code and deal with it in another PR. I'm not very keen on using erl_tidy for the auto-indent, since VSCode surely should support something as basic as that. erl_tidy (or some other solution which uses an external tool) would be useful for auto-formatting but I think the user should enable it using some switch.

It would be great if you could add your name to the News section e.g., Experimental workspace modules .... (contributed by YOUR NAME) if you don't mind.

Thanks a lot for all of the hard work you've put in this PR.

**Comment by yuce** [comment]
@frepond I've pushed a PR which fixes and improves auto indent in the extension: https://github.com/yuce/erlang-vscode/pull/8 Does it work for you?

**Comment by frepond** [comment]
Hi @yuce. I was a bit busy this week, I'll take a look.

**Comment by frepond** [comment]
Hi @yuce, configuration for formatting looks good. Also I see you have worked on indentation rules. I've also worked on them too, would you mind taking a look at them.

Also I've added ctags generation command for Erlang suitable to use with [ctags](https://marketplace.visualstudio.com/items?itemName=jaydenlin.ctags-support) which probably should be optional too.

**Comment by yuce** [comment]
Hi @frepond, the PR is doing a few things together (and getting more complex every day), which makes it hard to review. Do you mind creating a new PR with only the code completion related code? If ctags is a dependency, it would be nice to add a preference item which the user enables in order to use it.

I see that you've added code snippets. Which is nice but not sure including a copyright notice for "NGINEO LIMITED" is a very good idea :)

I've merged my auto-indent changes to master; it works for most of the cases I've tried (except `receive .. after` which seems to not easy to implement with indent rules) so I think auto format is not needed (until we find a more robust way to do it).

**Comment by frepond** [comment]
Yes @yuce sorry for that. I've modified it to suite our workflow at end. I won't be modifying it any further.

**Comment by yuce** [comment]
Sorry, I won't be able to merge this PR in its current form. You're welcome to open another PR if you change your mind. Thanks.

**Comment by frepond** [comment]
Hi @yuce,

I understand. Just let me know which features do you want to merge and I’ll cleanup it if you’re still interested.

Kind Regards,

Federico

**Comment by yuce** [comment]
Hi Federico,

I've checked the PR again. Ctags auto completion depends on the `ctags` utility (obviously) AND on another plugin and that plugin doesn't work the way VS Code users would expect it to work (e.g., navigating functions, etc.). While reading about ctags I came across Erlang's `tags` module: http://erlang.org/doc/man/tags.html . I think making use of that is a better option. So I think we should leave out this feature for now.

Would it be possible for you to create a new PR for the rebar3 related features you've added? It would be great if you could add a preference item for the rebar3 path so our users would specify where their rebar3 binary is.

Thanks and have a great day,

Yuce

**Comment by frepond** [comment]
Yes I can add rebar3 features and a preference for the path. What about workspace completions?

**Comment by yuce** [comment]
Thanks!

I think the best way to deal with completions is making use of a language server. Having said that, I've skimmed the workspace completion code. As far as I see that feature requires the user to run a command to create the list of completion items (and probably refresh that list too). Is that correct? If so, I think that's not very practical to use.

Would it make sense if we focus on the rebar3 PR before deciding on other features?

**Pull request closed without merging**
